#!/bin/sh

# a simple little script to generate test coverage data
# adjust as you require
# requires figleaf from:
# http://darcs.idyll.org/~t/projects/figleaf/doc/

find example -name "*.py" > interesting_files.txt
rm -rf html
rm -f .figleaf
figleaf $PYTHONPATH/py.test test
figleaf2html -f interesting_files.txt